apiVersion: v1   # API Version is required can check in cluster info
kind: Pod
metadata:
   name: demo2
spec:              # Specification we want in this pod
  containers:
    - name: nginx
      image: nginx
    - name: mongo
      image: mongo
