apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3

---

apiVersion: v1   # API Version is required can check in cluster info
kind: Pod
metadata:
   name: demo2
     labels:
       app: guestbook
       tier: frontend
spec:              # Specification we want in this pod
  containers:
    - name: nginx
      image: nginx

