apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    tier: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app1
  template:
    metadata:
      labels:
        tier: app1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
---

apiVersion: v1
kind: Service    # service is used to expose network app enable cluster IP that dont changes
metadata:
   name: frontend-cip # CIP means cluster IP service we are using
spec:
  selector:
     tier: app1 # this will select list of pods above we have
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service    # service is used to expose network app enable cluster IP that dont changes
metadata:
   name: frontend-np
spec:
  type: NodePort   # NP is Mode port service we are using
  selector:
     tier: app1 # this will select list of pods above we have
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

